import argparse
from pathlib import Path

from paradigm.data.rdm_export import export_chronometric_summary, export_ddm_ready_table, export_psychometric_summary, load_normalized_rdm_rows


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export psychometric and DDM-ready tables from an RDM trial summary CSV")
    parser.add_argument("trial_summary", help="Path to trial_summary.csv generated by the RDM task")
    parser.add_argument("--output-dir", default=None, help="Output directory; defaults to the trial summary directory")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    trial_summary_path = Path(args.trial_summary)
    output_dir = Path(args.output_dir) if args.output_dir else trial_summary_path.parent
    rows = load_normalized_rdm_rows(trial_summary_path)
    export_psychometric_summary(rows, output_dir / "rdm_psychometric_summary.csv")
    export_chronometric_summary(rows, output_dir / "rdm_chronometric_summary.csv")
    export_ddm_ready_table(rows, output_dir / "rdm_ddm_ready.csv")


if __name__ == "__main__":
    main()