import argparse
import csv
import json
from pathlib import Path

from paradigm.tasks.rdm import RDMTask


def read_trial_rows(trial_summary_path: Path) -> list[dict]:
    with trial_summary_path.open("r", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def normalize_rows(rows: list[dict]) -> list[dict]:
    normalized: list[dict] = []
    for row in rows:
        task_specific = row.get("task_specific_data")
        task_specific_payload = json.loads(task_specific) if isinstance(task_specific, str) and task_specific.strip().startswith("{") else {}
        exclude_trial_value = task_specific_payload.get("exclude_trial")
        normalized.append(
            {
                "trial_index": int(row["trial_index"]) if row.get("trial_index") else None,
                "coherence": float(task_specific_payload["coherence"]) if task_specific_payload.get("coherence") not in {None, "", "None"} else None,
                "direction": task_specific_payload.get("direction"),
                "response": row.get("response"),
                "correct": row.get("correct") in {"True", "true", True},
                "rt": float(row["rt"]) if row.get("rt") not in {None, "", "None"} else None,
                "timeout": row.get("timeout") in {"True", "true", True},
                "response_locked_rt": float(task_specific_payload["response_locked_rt"]) if task_specific_payload.get("response_locked_rt") not in {None, "", "None"} else None,
                "cpp_slope_proxy": float(task_specific_payload["cpp_slope_proxy"]) if task_specific_payload.get("cpp_slope_proxy") not in {None, "", "None"} else None,
                "exclude_trial": exclude_trial_value in {"True", "true", True} if exclude_trial_value not in {None, "", "None"} else None,
                "exclude_reason": task_specific_payload.get("exclude_reason"),
            }
        )
    return normalized



def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export psychometric and DDM-ready tables from an RDM trial summary CSV")
    parser.add_argument("trial_summary", help="Path to trial_summary.csv generated by the RDM task")
    parser.add_argument("--output-dir", default=None, help="Output directory; defaults to the trial summary directory")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    trial_summary_path = Path(args.trial_summary)
    output_dir = Path(args.output_dir) if args.output_dir else trial_summary_path.parent
    rows = normalize_rows(read_trial_rows(trial_summary_path))
    RDMTask.export_psychometric_summary(rows, output_dir / "rdm_psychometric_summary.csv")
    RDMTask.export_ddm_ready_table(rows, output_dir / "rdm_ddm_ready.csv")


if __name__ == "__main__":
    main()